spring:
  application:
    name: ScaleLink

  datasource:
    url: jdbc:postgresql://localhost:5432/scalelink
    username: somu
    password: somu
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

      rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest